name: WLED compile

on:
    workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.9

    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio
    - name: Set up Node.js
      uses: actions/setup-node@v4
    - name: Run PlatformIO
      run: |
        rm -rf /tmp/WLEDtemp/* || true
        mkdir -p /tmp/WLEDtemp
        wget https://api.github.com/repos/MoonModules/WLED-MM/zipball/v14.5.0-beta -O /tmp/WLEDtemp/mm.zip
        unzip /tmp/WLEDtemp/mm.zip -d /tmp/WLEDtemp
        find /tmp/WLEDtemp -maxdepth 1 -mindepth 1 -name "*" -type d >> /tmp/WLEDtemp/wledfoldername
        cd `cat /tmp/WLEDtemp/wledfoldername`
        npm install
        echo '[env:custom_build]' >>platformio.ini
        echo 'extends = env:esp32s3dev_16MB_PSRAM_opi' >>platformio.ini
        echo 'build_flags = ${env:esp32s3dev_16MB_PSRAM_opi.build_flags} -D WLED_DEBUG_NTP -D WLED_DEBUG_IMPROV -D WLED_ENABLE_MQTT -D WLED_ENABLE_LOXONE -D WLED_ENABLE_ADALIGHT -D WLED_ENABLE_PIXART -D WLED_DISABLE_ALEXA -D WLED_MAX_BUTTONS=2 -D WLED_MAX_BUSSES=6 -D ABL_MILLIAMPS_DEFAULT=850 -D WLED_MAX_LEDMAPS=156 -D MAX_LEDS=8192 -D MAX_LEDS_PER_BUS=2048 -D MAX_LED_MEMORY=64000 -D WLED_PWM_FREQ=19531 -D USERMOD_AUTO_SAVE -D USERMOD_ANIMATED_STAIRCASE -D USERMOD_ADS1115 -D USERMOD_HTTP_PULL_LIGHT_CONTROL' >>platformio.ini
        echo 'lib_deps = ' >>platformio.ini
        echo '  ${env:esp32s3dev_16MB_PSRAM_opi.lib_deps}' >>platformio.ini
        echo '  adafruit/Adafruit BusIO @ 1.13.2' >>platformio.ini
        echo '  adafruit/Adafruit ADS1X15 @ 2.4.0' >>platformio.ini
        echo '  adafruit/Adafruit Unified Sensor[env:custom_build]' >>platformio.ini
        echo 'extends = env:esp32s3dev_16MB_PSRAM_opi' >>platformio.ini
        echo 'build_flags = ${env:esp32s3dev_16MB_PSRAM_opi.build_flags} -D WLED_DEBUG_NTP -D WLED_DEBUG_IMPROV -D WLED_ENABLE_MQTT -D WLED_ENABLE_LOXONE -D WLED_ENABLE_ADALIGHT -D WLED_ENABLE_PIXART -D WLED_DISABLE_ALEXA -D WLED_MAX_BUTTONS=2 -D WLED_MAX_BUSSES=6 -D ABL_MILLIAMPS_DEFAULT=850 -D WLED_MAX_LEDMAPS=156 -D MAX_LEDS=8192 -D MAX_LEDS_PER_BUS=2048 -D MAX_LED_MEMORY=64000 -D WLED_PWM_FREQ=19531 -D USERMOD_AUTO_SAVE -D USERMOD_ANIMATED_STAIRCASE -D USERMOD_ADS1115 -D USERMOD_HTTP_PULL_LIGHT_CONTROL' >>platformio.ini
        echo 'lib_deps = ' >>platformio.ini
        echo '  ${env:esp32s3dev_16MB_PSRAM_opi.lib_deps}' >>platformio.ini
        echo '  adafruit/Adafruit BusIO @ 1.13.2' >>platformio.ini
        echo '  adafruit/Adafruit ADS1X15 @ 2.4.0' >>platformio.ini
        echo '  adafruit/Adafruit Unified Sensor[env:custom_build]' >>platformio.ini
        echo 'extends = env:esp32s3dev_16MB_PSRAM_opi' >>platformio.ini
        echo 'build_flags = ${env:esp32s3dev_16MB_PSRAM_opi.build_flags} -D WLED_DEBUG_NTP -D WLED_DEBUG_IMPROV -D WLED_ENABLE_MQTT -D WLED_ENABLE_LOXONE -D WLED_ENABLE_ADALIGHT -D WLED_ENABLE_PIXART -D WLED_DISABLE_ALEXA -D WLED_MAX_BUTTONS=2 -D WLED_MAX_BUSSES=6 -D ABL_MILLIAMPS_DEFAULT=850 -D WLED_MAX_LEDMAPS=156 -D MAX_LEDS=8192 -D MAX_LEDS_PER_BUS=2048 -D MAX_LED_MEMORY=64000 -D WLED_PWM_FREQ=19531 -D USERMOD_AUTO_SAVE -D USERMOD_ANIMATED_STAIRCASE -D USERMOD_ADS1115 -D USERMOD_HTTP_PULL_LIGHT_CONTROL' >>platformio.ini
        echo 'lib_deps = ' >>platformio.ini
        echo '  ${env:esp32s3dev_16MB_PSRAM_opi.lib_deps}' >>platformio.ini
        echo '  adafruit/Adafruit BusIO @ 1.13.2' >>platformio.ini
        echo '  adafruit/Adafruit ADS1X15 @ 2.4.0' >>platformio.ini
        echo '  adafruit/Adafruit Unified Sensor[env:custom_build]' >>platformio.ini
        echo 'extends = env:esp32s3dev_16MB_PSRAM_opi' >>platformio.ini
        echo 'build_flags = ${env:esp32s3dev_16MB_PSRAM_opi.build_flags} -D WLED_DEBUG_NTP -D WLED_DEBUG_IMPROV -D WLED_ENABLE_MQTT -D WLED_ENABLE_LOXONE -D WLED_ENABLE_ADALIGHT -D WLED_ENABLE_PIXART -D WLED_DISABLE_ALEXA -D WLED_MAX_BUTTONS=2 -D WLED_MAX_BUSSES=6 -D ABL_MILLIAMPS_DEFAULT=850 -D WLED_MAX_LEDMAPS=156 -D MAX_LEDS=8192 -D MAX_LEDS_PER_BUS=2048 -D MAX_LED_MEMORY=64000 -D WLED_PWM_FREQ=19531 -D USERMOD_AUTO_SAVE -D USERMOD_ANIMATED_STAIRCASE -D USERMOD_ADS1115 -D USERMOD_HTTP_PULL_LIGHT_CONTROL' >>platformio.ini
        echo 'lib_deps = ' >>platformio.ini
        echo '  ${env:esp32s3dev_16MB_PSRAM_opi.lib_deps}' >>platformio.ini
        echo '  adafruit/Adafruit BusIO @ 1.13.2' >>platformio.ini
        echo '  adafruit/Adafruit ADS1X15 @ 2.4.0' >>platformio.ini
        echo '  adafruit/Adafruit Unified Sensor[env:custom_build]' >>platformio.ini
        echo 'extends = env:esp32s3dev_16MB_PSRAM_opi' >>platformio.ini
        echo 'build_flags = ${env:esp32s3dev_16MB_PSRAM_opi.build_flags} -D WLED_DEBUG_NTP -D WLED_DEBUG_IMPROV -D WLED_ENABLE_MQTT -D WLED_ENABLE_LOXONE -D WLED_ENABLE_ADALIGHT -D WLED_ENABLE_PIXART -D WLED_DISABLE_ALEXA -D WLED_MAX_BUTTONS=2 -D WLED_MAX_BUSSES=6 -D ABL_MILLIAMPS_DEFAULT=850 -D WLED_MAX_LEDMAPS=156 -D MAX_LEDS=8192 -D MAX_LEDS_PER_BUS=2048 -D MAX_LED_MEMORY=64000 -D WLED_PWM_FREQ=19531 -D USERMOD_AUTO_SAVE -D USERMOD_ANIMATED_STAIRCASE -D USERMOD_ADS1115 -D USERMOD_HTTP_PULL_LIGHT_CONTROL' >>platformio.ini
        echo 'lib_deps = ' >>platformio.ini
        echo '  ${env:esp32s3dev_16MB_PSRAM_opi.lib_deps}' >>platformio.ini
        echo '  adafruit/Adafruit BusIO @ 1.13.2' >>platformio.ini
        echo '  adafruit/Adafruit ADS1X15 @ 2.4.0' >>platformio.ini
        echo '  adafruit/Adafruit Unified Sensorvvvvvvvvvvvvvv' >>platformio.ini
        
        echo 'build_unflags= -D WLED_RELEASE_NAME' >>platformio.ini
        pio run -e custom_build || pio run -e custom_build
    - name: Copy Files
      run: |
        cd $GITHUB_WORKSPACE
        git rm -r $GITHUB_WORKSPACE/*.bin || true
        WLEDFOLDERNAME=`cat /tmp/WLEDtemp/wledfoldername`
        cp ${WLEDFOLDERNAME}/build_output/firmware/custom_build.bin $GITHUB_WORKSPACE/
        date -I | tr -d '\n' >$GITHUB_WORKSPACE/last_update_date.txt
    - name: Commit Files
      run: |
        cd $GITHUB_WORKSPACE
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
        git add $GITHUB_WORKSPACE/custom_build.bin
        git add $GITHUB_WORKSPACE/last_update_date.txt
        git commit -m "Commit Custom Build"
        git push origin main
