[env:custom_build]
extends = env:esp32s3dev_16MB_PSRAM_opi
build_flags = ${env:esp32s3dev_16MB_PSRAM_opi.build_flags} -D WLED_DEBUG_NTP -D WLED_DEBUG_IMPROV -D WLED_ENABLE_MQTT -D WLED_ENABLE_LOXONE -D WLED_ENABLE_ADALIGHT -D WLED_ENABLE_PIXART -D WLED_DISABLE_ALEXA -D WLED_MAX_BUTTONS=2 -D WLED_MAX_BUSSES=6 -D ABL_MILLIAMPS_DEFAULT=850 -D WLED_MAX_LEDMAPS=156 -D MAX_LEDS=8192 -D MAX_LEDS_PER_BUS=2048 -D MAX_LED_MEMORY=64000 -D WLED_PWM_FREQ=19531 -D USERMOD_AUTO_SAVE -D USERMOD_ANIMATED_STAIRCASE -D USERMOD_ADS1115 -D USERMOD_HTTP_PULL_LIGHT_CONTROL
lib_deps = 
  ${env:esp32s3dev_16MB_PSRAM_opi.lib_deps}
  adafruit/Adafruit BusIO @ 1.13.2
  adafruit/Adafruit ADS1X15 @ 2.4.0
  adafruit/Adafruit Unified Sensor
